apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectctt4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectctt4
  template:
    metadata:
      labels:
        app: projectctt4
    spec:  # Indentation corrected here
      containers:
      - name: projectctt4-webfront-1
        image: projectctt4-webfront:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: projectctt4
  ports:
    - protocol: TCP
      port: 80  # Expose your application on this port
      targetPort: 80  # Your application inside the container listens on this port
      nodePort: 30329  # Change the NodePort to a different value
  type: NodePort
